using System;
using UnityEngine;

namespace Ascent.Managers.Input
{
    public enum MappableKeys
    {
        Alpha1 = KeyCode.Alpha1,
        Alpha2 = KeyCode.Alpha2,
        Alpha3 = KeyCode.Alpha3,
        Alpha4 = KeyCode.Alpha4,
        Alpha5 = KeyCode.Alpha5,
        Alpha6 = KeyCode.Alpha6,
        Alpha7 = KeyCode.Alpha7,
        Alpha8 = KeyCode.Alpha8,
        Alpha9 = KeyCode.Alpha9,
        Alpha0 = KeyCode.Alpha0,
    
        Keypad1 = KeyCode.Keypad1,
        Keypad2 = KeyCode.Keypad2,
        Keypad3 = KeyCode.Keypad3,
        Keypad4 = KeyCode.Keypad4,
        Keypad5 = KeyCode.Keypad5,
        Keypad6 = KeyCode.Keypad6,
        Keypad7 = KeyCode.Keypad7,
        Keypad8 = KeyCode.Keypad8,
        Keypad9 = KeyCode.Keypad9,
        Keypad0 = KeyCode.Keypad0,
        KeypadPeriod = KeyCode.KeypadPeriod,
        KeypadDivide = KeyCode.KeypadDivide,
        KeypadMultiply = KeyCode.KeypadMultiply,
        KeypadMinus = KeyCode.KeypadMinus,
        KeypadPlus = KeyCode.KeypadPlus,
        KeypadEnter = KeyCode.KeypadEnter,
        KeypadEquals = KeyCode.KeypadEquals,
    
        Q = KeyCode.Q,
        W = KeyCode.W,
        E = KeyCode.E,
        R = KeyCode.R,
        T = KeyCode.T,
        Y = KeyCode.Y,
        U = KeyCode.U,
        I = KeyCode.I,
        O = KeyCode.O,
        P = KeyCode.P,
        A = KeyCode.A,
        S = KeyCode.S,
        D = KeyCode.D,
        F = KeyCode.F,
        G = KeyCode.G,
        H = KeyCode.H,
        J = KeyCode.J,
        K = KeyCode.K,
        L = KeyCode.L,
        Z = KeyCode.Z,
        X = KeyCode.X,
        C = KeyCode.C,
        V = KeyCode.V,
        B = KeyCode.B,
        N = KeyCode.N,
        M = KeyCode.M,
    
        Escape = KeyCode.Escape,
        BackQuote = KeyCode.BackQuote,
        Tab = KeyCode.Tab,
        CapsLock = KeyCode.CapsLock,
        LeftShift = KeyCode.LeftShift,
        RightShift = KeyCode.RightShift,
        LeftControl = KeyCode.LeftControl,
        RightControl = KeyCode.RightControl,
        LeftAlt = KeyCode.LeftAlt,
        RightAlt = KeyCode.RightAlt,
    
        Backspace = KeyCode.Backspace,
        Minus = KeyCode.Minus,
        Equals = KeyCode.Equals,
        LeftBracket = KeyCode.LeftBracket,
        RightBracket = KeyCode.RightBracket,
        Semicolon = KeyCode.Semicolon,
        Quote = KeyCode.Quote,
        Comma = KeyCode.Comma,
        Period = KeyCode.Period,
        Slash = KeyCode.Slash,
        Backslash = KeyCode.Backslash,
        Return = KeyCode.Return,
    
        UpArrow = KeyCode.UpArrow,
        DownArrow = KeyCode.DownArrow,
        LeftArrow = KeyCode.LeftArrow,
        RightArrow = KeyCode.RightArrow,
    
        Insert = KeyCode.Insert,
        Home = KeyCode.Home,
        Delete = KeyCode.Delete,
        End = KeyCode.End,
        PageUp = KeyCode.PageUp,
        PageDown = KeyCode.PageDown,
        Space = KeyCode.Space,
    
        F1 = KeyCode.F1,
        F2 = KeyCode.F2,
        F3 = KeyCode.F3,
        F4 = KeyCode.F4,
        F5 = KeyCode.F5,
        F6 = KeyCode.F6,
        F7 = KeyCode.F7,
        F8 = KeyCode.F8,
        F9 = KeyCode.F9,
        F10 = KeyCode.F10,
        F11 = KeyCode.F11,
        F12 = KeyCode.F12,
    }
}
